# Generated by Django 5.2.6 on 2025-09-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('keywords', models.JSONField(help_text="e.g., ['Python', 'Kubernetes']")),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('ACTION_VERB', 'Action Verb Check'), ('METRIC', 'Metric Presence'), ('KEYWORD', 'Keyword Relevance'), ('GRAMMAR', 'Grammar Clarity')], max_length=20)),
                ('config', models.JSONField()),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
