# Generated by Django 5.2.6 on 2025-09-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('keywords', models.JSONField(help_text="e.g., ['Python', 'Docker', 'CI/CD']")),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EvaluationRule',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='keywords',
            field=models.JSONField(),
        ),
    ]
